### ISSUE TITLE
Mirrors don't work with portals

### ISSUE THREAD

**Issue by davidthehat** [qouteall/ImmersivePortalsModForForge#14]
Mirrors tend to ignore portals. When in the same dimension, mirrors allow you to see right though the portal. When in a different dimension than the mirror, the mirror displays a weird, zoomed image that is difficult to describe.
![2020-01-14_08 52 13](https://user-images.githubusercontent.com/24359213/72349830-413c4d80-36ab-11ea-907f-7d689c97b38e.png)
![2020-01-14_08 52 37](https://user-images.githubusercontent.com/24359213/72349831-41d4e400-36ab-11ea-85af-c5678d787291.png)

**Comment by qouteall** [comment]
Rendering mirror-in-mirror, portal-in-mirror, and mirror-in-portal are a little bit hard because coordinate inconsistencies. Minecraft uses player-centered non-rotated coordination for rendering and in my current approach the origin is not the position of camera when rendering mirrors. I will fix this when I figure out the math.
