### ISSUE TITLE
[Uninstall issue] Unable to play minecraft after removing immersive portals

### ISSUE THREAD

**Issue by Shibva** [qouteall/ImmersivePortalsModForForge#297]
Idk what's going on but when I remove the mod and whether it's joining an existing world and create a new world the game screen will go black after moving some blocks and I get a black screen and then moments later get an internal error. It's not a crash but the game refuses to let me play and the only way to fix this issue is to Reinstall the mod. Idk what todo and I feel trapped. I don't want to have to wipe my instance to fix this but idk what todo

Anyone know what's going on? Please respond ASAP

**Comment by qouteall** [comment]
Removing this mod normally should not affect new world creation. Maybe the issue is related to other mods.

Someone reported that after removing IP other people cannot join LAN world. There are two ways to fix this
1. If the world doesn't contain things of other mods, you can use vanilla Minecraft to open the world once.
2. Create another world with the same seed and name, then use the new `level.dat` to override the old one.

**Comment by Shibva** [comment]
never mind, found out it was another mod causing it, though it did need IP for it to work correctly
